### ISSUE TITLE
Quick Map Services fails on QGis 2.17

### ISSUE THREAD

**Issue by Komzpa** [nextgis/quickmapservices#107]
```
Traceback (most recent call last):
              File "/home/kom/.qgis-dev//python/plugins/quick_map_services/py_tiled_layer/tilelayer.py", line 316, in draw
                self.drawTilesOnTheFly(renderContext, self.tiles)
              File "/home/kom/.qgis-dev//python/plugins/quick_map_services/py_tiled_layer/tilelayer.py", line 410, in drawTilesOnTheFly
                canvas_ds.SetProjection(str(transform.destCRS().toWkt()))
            AttributeError: 'QgsCoordinateTransform' object has no attribute 'destCRS'
```

**Comment by 514ckw4r3** [comment]
@Komzpa, Is this issue still relevant? I checked this issue on QGIS 2.16 and it didn't reproduce.

**Comment by Komzpa** [comment]
It's been 5 years and a major version change.
