### ISSUE TITLE
Uncaught UnicodeEncodeError: 'ascii' codec can't encode characters in position 13-22: ordinal not in range(128)


### ISSUE THREAD

**Issue by peter-shr** [nextgis/quickmapservices#115]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/user/.qgis2/python/plugins\quick_map_services\qms_service_toolbox.py", line 155, in show_result
    custom_widget = QmsSearchResultItemWidget(geoservice, image_ba)
  File "C:/Users/user/.qgis2/python/plugins\quick_map_services\qms_service_toolbox.py", line 233, in __init__
    Client().geoservice_info_url(geoservice.get('id', ""))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 13-22: ordinal not in range(128)

```
quick_map_services 0.18, QGIS 2.14.10-Essen on Windows 8

**Comment by simgislab** [comment]
thanks for quick report, please reinstall the plugin (we didn't bump change version)
