### ISSUE TITLE
Add group crash in qms settings

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/quickmapservices#137]
Stack trace

```
Ошибка при выполнении сценария Python: 

IOError: [Errno 2] No such file or directory: '/Users/Bishop/.config/NextGIS/qgis2/python/plugins/quick_map_services/icons/mapservice.png' 
Traceback (most recent call last):
  File "/Users/Bishop/.config/NextGIS/qgis2/python/plugins/quick_map_services/group_edit_dialog.py", line 92, in accept
    res = self.create_new()
  File "/Users/Bishop/.config/NextGIS/qgis2/python/plugins/quick_map_services/group_edit_dialog.py", line 200, in create_new
    shutil.copy(group_icon, ico_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/Users/Bishop/.config/NextGIS/qgis2/python/plugins/quick_map_services/icons/mapservice.png'


Версия Python: 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] 
Версия: 2.14.15-Essen Essen, 17.6.0 

Расположение Python:
/Users/Bishop/Applications/NextGIS/Applications/ngqgis.app/Contents/Resources/python/plugins/processing
/Users/Bishop/Applications/NextGIS/Applications/ngqgis.app/Contents/Resources/python
/Users/Bishop/.config/NextGIS/qgis2/python
/Users/Bishop/.config/NextGIS/qgis2/python/plugins
/Users/Bishop/Applications/NextGIS/Applications/ngqgis.app/Contents/Resources/python/plugins
/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/Users/Bishop/Library/Python/2.7/lib/python/site-packages
/Users/Bishop/Applications/NextGIS/Library/Python/2.7/site-packages
/Users/Bishop/Library/Python/2.7/lib/python/site-packages/PyObjC
/Library/Python/2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
/Users/Bishop/.config/NextGIS/qgis2/python
/Users/Bishop/Applications/NextGIS/Applications/ngqgis.app/Contents/Resources/python/plugins/fTools/tools
/Users/Bishop/tmp/mow
```

Expected behaviour not crash and add group without icon

**Comment by simgislab** [comment]
создается, не крашится
