### ISSUE TITLE
Creating group error

### ISSUE THREAD

**Issue by alisovenko** [nextgis/quickmapservices#159]
An error has occurred while executing Python code: 

AttributeError: 'tuple' object has no attribute 'rfind' 
Traceback (most recent call last):
  File "/home/rykov/.local/share/QGIS/QGIS3/profiles/default/python/plugins/quick_map_services/group_edit_dialog.py", line 93, in accept
    res = self.create_new()
  File "/home/rykov/.local/share/QGIS/QGIS3/profiles/default/python/plugins/quick_map_services/group_edit_dialog.py", line 194, in create_new
    ico_file_name = path.basename(group_icon)
  File "/usr/lib/python3.5/posixpath.py", line 139, in basename
    i = p.rfind(sep) + 1
AttributeError: 'tuple' object has no attribute 'rfind'

**Comment by alisovenko** [comment]
Done in 43d1def
