### ISSUE TITLE
QGIS 3.0.1 - Invalid WMS Layer causes crash

### ISSUE THREAD

**Issue by ingalls** [nextgis/quickmapservices#160]
QuickMapServices Plugin crashed when attempting to add a new custom WMS layer.

Steps Taken Before Crash:

- Opened QMS Settings pane via `Web > QuickMapServices > Settings`
- navigated to `Add\Edit\Remove` tab
- Clicked `+` in `My Services` pane
- Filled out Form

| Property | Value |
| --- | --- |
| ID | `MapboxStreets` |
| Alias | `Mapbox Streets` |
| Icon | Didn't change |
| Group | `OSM` |
| Type | `WMS` |

- Left License Fields Blank
- WMS - Enter an invalid layer or params and click add. QMS will crash with the error below.

Operating System: Ubuntu 17.04
Python Version: 3.6.3 (default, Oct  3 2017, 21:45:48) [GCC 7.2.0] 
QGIS Version: 3.0.1-Girona Girona, a86bec2 

Error Thrown:
```
TypeError: expected str, bytes or os.PathLike object, not tuple 
Traceback (most recent call last):
  File "/home/null/.local/share/QGIS/QGIS3/profiles/default/python/plugins/quick_map_services/ds_edit_dialog.py", line 163, in accept
    self.feel_ds_info(new_ds_info)
  File "/home/null/.local/share/QGIS/QGIS3/profiles/default/python/plugins/quick_map_services/ds_edit_dialog.py", line 262, in feel_ds_info
    ds_info.icon = os.path.basename(self.__ds_icon)
  File "/usr/lib/python3.6/posixpath.py", line 144, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not tuple
```

**Comment by alisovenko** [comment]
Please try version 0.19.7
