### ISSUE TITLE
QMS installs, but can't be turned on

### ISSUE THREAD

**Issue by simgislab** [nextgis/quickmapservices#161]
QGIS3 is on the same machine and QMS works fine on it.

```
Не удалось загрузить модуль quick_map_services из-за ошибки при вызове его метода initGui() 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128) 
Traceback (most recent call last):
  File "C:/OSGeo4w/apps/qgis-ltr/./python\qgis\utils.py", line 342, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/Sim/.qgis2/python/plugins\quick_map_services\quick_map_services.py", line 121, in initGui
    self.init_server_panel()
  File "C:/Users/Sim/.qgis2/python/plugins\quick_map_services\quick_map_services.py", line 311, in init_server_panel
    self.server_toolbox = QmsServiceToolbox(self.iface)
  File "C:/Users/Sim/.qgis2/python/plugins\quick_map_services\qms_service_toolbox.py", line 153, in __init__
    self.add_last_used_services()
  File "C:/Users/Sim/.qgis2/python/plugins\quick_map_services\qms_service_toolbox.py", line 247, in add_last_used_services
    image_qByteArray
  File "C:/Users/Sim/.qgis2/python/plugins\quick_map_services\qms_service_toolbox.py", line 357, in __init__
    self.service_name.setText(u"    {} ".format(geoservice.get('name', u"")))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)


Версия Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Версия: 2.18.18 Las Palmas, b33566195a 

Расположение Python:
C:/OSGeo4w/apps/qgis-ltr/./python/plugins\processing
C:/OSGeo4w/apps/qgis-ltr/./python
C:/Users/Sim/.qgis2/python
C:/Users/Sim/.qgis2/python/plugins
C:/OSGeo4w/apps/qgis-ltr/./python/plugins
C:\OSGeo4w\bin\python27.zip
C:\OSGeo4w\apps\Python27\DLLs
C:\OSGeo4w\apps\Python27\lib
C:\OSGeo4w\apps\Python27\lib\plat-win
C:\OSGeo4w\apps\Python27\lib\lib-tk
C:\OSGeo4w\bin
C:\OSGeo4w\apps\Python27
C:\OSGeo4w\apps\Python27\lib\site-packages
C:\OSGeo4w\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\OSGeo4w\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:/Users/Sim/.qgis2//python
```

**Comment by simgislab** [comment]
same problem on Ubuntu

**Comment by simgislab** [comment]
works fine on NGQ 18.4

**Comment by alisovenko** [comment]
Done
