### ISSUE TITLE
ngqgis 18.4 QMS fails to install (ubuntu 17.10)

### ISSUE THREAD

**Issue by trolleway** [nextgis/quickmapservices#163]
Свежая ubuntu 17.10
Поставил сначала qgis из репозитория qgis, потом ngqgis из нашего репозитория
![screenshot from 2018-04-19 14-58-08](https://user-images.githubusercontent.com/4630662/38990336-861b9888-43e2-11e8-88e6-8911afd8385e.png)

```
Couldn't load plugin quick_map_services due to an error when calling its initGui() method 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 6: ordinal not in range(128) 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 361, in startPlugin
    plugins[packageName].initGui()
  File "/home/trolleway/.config/NextGIS/qgis2/python/plugins/quick_map_services/quick_map_services.py", line 121, in initGui
    self.init_server_panel()
  File "/home/trolleway/.config/NextGIS/qgis2/python/plugins/quick_map_services/quick_map_services.py", line 311, in init_server_panel
    self.server_toolbox = QmsServiceToolbox(self.iface)
  File "/home/trolleway/.config/NextGIS/qgis2/python/plugins/quick_map_services/qms_service_toolbox.py", line 153, in __init__
    self.add_last_used_services()
  File "/home/trolleway/.config/NextGIS/qgis2/python/plugins/quick_map_services/qms_service_toolbox.py", line 247, in add_last_used_services
    image_qByteArray
  File "/home/trolleway/.config/NextGIS/qgis2/python/plugins/quick_map_services/qms_service_toolbox.py", line 357, in __init__
    self.service_name.setText(u"    {} ".format(geoservice.get('name', u"")))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 6: ordinal not in range(128)


Python version: 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0] 
QGIS version: 2.18.18-Las Palmas Las Palmas, 18.4.0 

Python Path:
/usr/share/ngqgis/python/plugins/processing
/usr/share/ngqgis/python
/home/trolleway/.config/NextGIS/qgis2/python
/home/trolleway/.config/NextGIS/qgis2/python/plugins
/usr/share/ngqgis/python/plugins
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gtk-2.0
/home/trolleway/.config/NextGIS/qgis2/python
/usr/share/ngqgis/python/plugins/fTools/tools
```

**Comment by trolleway** [comment]
У меня в хидере окна QGIS написано 18.4.0

**Comment by simgislab** [comment]
duplicate of https://github.com/nextgis/quickmapservices/issues/161
