### ISSUE TITLE
Uncaught ImportError: No module named client


### ISSUE THREAD

**Issue by peter-shr** [nextgis/quickmapservices#170]
Konnte Erweiterung quick_map_services nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/USER/.qgis2/python/plugins\quick_map_services\__init__.py", line 34, in classFactory
    from .quick_map_services import QuickMapServices
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/USER/.qgis2/python/plugins\quick_map_services\quick_map_services.py", line 41, in <module>
    from .qms_service_toolbox import QmsServiceToolbox
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/USER/.qgis2/python/plugins\quick_map_services\qms_service_toolbox.py", line 47, in <module>
    from .qms_external_api_python.client import Client
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named client

```
quick_map_services 0.19.10, QGIS 2.18.21 on Windows 10

**Comment by simgislab** [comment]
can you update QMS and check it again?
