### ISSUE TITLE
ImportError: No module named 'quick_map_services.qms_external_api_python' 

### ISSUE THREAD

**Issue by SrNetoChan** [nextgis/quickmapservices#171]
I have install the most recent version of the plugin using plugin manager.

When I try to activate I get the following error:

```
Couldn't load plugin 'quick_map_services' due to an error when calling its classFactory() method 

ImportError: No module named 'quick_map_services.qms_external_api_python' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/alexandre/.local/share/QGIS/QGIS3/profiles/alexandre/python/plugins/quick_map_services/__init__.py", line 34, in classFactory
    from .quick_map_services import QuickMapServices
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 665, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alexandre/.local/share/QGIS/QGIS3/profiles/alexandre/python/plugins/quick_map_services/quick_map_services.py", line 41, in 
    from .qms_service_toolbox import QmsServiceToolbox
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 665, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/alexandre/.local/share/QGIS/QGIS3/profiles/alexandre/python/plugins/quick_map_services/qms_service_toolbox.py", line 47, in 
    from .qms_external_api_python.client import Client
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 665, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 665, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named 'quick_map_services.qms_external_api_python'


Python version: 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609] 
QGIS version: 3.2.0-Bonn Bonn, bc43194 

Python Path:
/usr/share/qgis/python
/home/alexandre/.local/share/QGIS/QGIS3/profiles/alexandre/python
/home/alexandre/.local/share/QGIS/QGIS3/profiles/alexandre/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python35.zip
/usr/lib/python3.5
/usr/lib/python3.5/plat-x86_64-linux-gnu
/usr/lib/python3.5/lib-dynload
/usr/local/lib/python3.5/dist-packages
/usr/lib/python3/dist-packages
/home/alexandre/.local/share/QGIS/QGIS3/profiles/alexandre/python
```

**Comment by SrNetoChan** [comment]
Forgot to mention that I am using QGIS 3.2 on a 16.04 ubuntu 64bit machine. thanks

**Comment by james-berry** [comment]
+

**Comment by alisovenko** [comment]
Please, try to update to 0.19.10.1

**Comment by SrNetoChan** [comment]
Works fine now! thanks
