### ISSUE TITLE
Error on loading plugin QGIS 3.4.8

### ISSUE THREAD

**Issue by 4estone** [nextgis/quickmapservices#198]
When loading plugin, I get 
TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/sylvain.pierre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\__init__.py", line 35, in classFactory
    return QuickMapServices(iface)
  File "C:/Users/sylvain.pierre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\quick_map_services.py", line 72, in __init__
    self.locale = Locale.get_locale()
  File "C:/Users/sylvain.pierre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\quick_map_services\plugin_locale.py", line 30, in get_locale
    return QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.4.8-Madeira Madeira, 04ee8e0761

**Comment by 514ckw4r3** [comment]
Duplicate https://github.com/nextgis/quickmapservices/issues/174
