### ISSUE TITLE
ZeroDivisionError since QGIS 3.20

### ISSUE THREAD

**Issue by s6hebern** [nextgis/quickmapservices#221]
With the new QGIS 3.20, I now get the following error (for any basemap):

```
An error has occurred while executing Python code: 

ZeroDivisionError: float division by zero 
Traceback (most recent call last):
  File "C:\Users/USERNAME/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\valuetool\valuewidget.py", line 432, in printValue
    ident = self.getValue(layer, pos, activeBands)
  File "C:\Users/USERNAME/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\valuetool\valuewidget.py", line 303, in getRowCol
    extent = layer.dataProvider().extent()
ZeroDivisionError: float division by zero


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.20.0-Odense Odense, decaadbb31 
```

In reality, it seems to have no effect, all basemaps load and display perfectly fine. Just an annoying message to click away every time.

**Comment by 514ckw4r3** [comment]
This is an error message of the "valuetool" plugin, not quickmapservices.

**Comment by s6hebern** [comment]
Oh heck... sorry! Did not realize that, since it only appears when I use QuickMapServices. Nevermind...
