### ISSUE TITLE
Unable to load plugin 'quick_map_services' because an error occurred while calling its classFactory() method

### ISSUE THREAD

**Issue by Yuanen-Pang** [nextgis/quickmapservices#254]
**Dear developer, Today I reinstall your esteemed plug, but I meet the following error. It seems that the Qt version in your code is not compatible with older versions of qgis?**
AttributeError: 'QTabWidget' object has no attribute 'setTabVisible' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/123/.local/share/QGIS/QGIS3/profiles/default/python/plugins/quick_map_services/__init__.py", line 36, in classFactory
    return QuickMapServices(iface)
  File "/home/123/.local/share/QGIS/QGIS3/profiles/default/python/plugins/quick_map_services/quick_map_services.py", line 98, in __init__
    self.info_dlg = AboutDialog(os.path.basename(self.plugin_dir))
  File "/home/123/.local/share/QGIS/QGIS3/profiles/default/python/plugins/quick_map_services/about_dialog.py", line 38, in __init__
    self.__fill_license()
  File "/home/123/.local/share/QGIS/QGIS3/profiles/default/python/plugins/quick_map_services/about_dialog.py", line 118, in __fill_license
    self.tab_widget.setTabVisible(AboutTab.License, True)
AttributeError: 'QTabWidget' object has no attribute 'setTabVisible'

**Python version： 3.8.10 (default, Nov  7 2024, 13:10:47) [GCC 9.4.0] 
QGIS version： 3.26.3-Buenos Aires Buenos Aires, 65e4edfdad** 

Python path：
/usr/share/qgis/python
/home/123/.local/share/QGIS/QGIS3/profiles/default/python
/home/123/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/123/.local/share/QGIS/QGIS3/profiles/default/python

**Comment by Yuanen-Pang** [comment]
OS is ubuntu 20.04. QGIS version is 3.26. Actually it does work well before I update this plug, but the error appear after I update it.

**Comment by RemeshevskiyValeriy** [comment]
Hi! Thank you so much for pointing out the problem. We fixed the problem, you can update the plugin to the new version. We will be glad to receive your feedback.

**Comment by Yuanen-Pang** [comment]
It's ok now  :) Thanks for your contribution!

**Comment by RemeshevskiyValeriy** [comment]
Great! Thank you for your feedback <3
