### ISSUE TITLE
Plugin load error when non-ASCII characters exists in qgis user directory path

### ISSUE THREAD

**Issue by drnextgis** [nextgis/quickmapservices#28]
Вот прислали тут скриншот.

![img-20150608-wa0002](https://cloud.githubusercontent.com/assets/866124/8039754/4d52852a-0e25-11e5-82d4-8daed5fee3b8.jpg)

**Comment by yellow-sky** [comment]
Желателен текст сообщения а не скриншот.
То что отображается в окне криво - не факт что ошибка в путях.

Попробую воспроизвести на венде.

**Comment by drnextgis** [comment]
Согласен, но после того как был заведен новый пользователь и из под него был переустановлен QGIS и модуль - ошибка исчезла.

**Comment by simgislab** [comment]
Подтверждаю ошибку. Если пользователь назван "Пользователь" модуль не стартует. Не успел записать ошибку, увы.

**Comment by drnextgis** [comment]
```
Не удалось загрузить модуль quick_map_services из-за ошибки при вызове его метода initGui()


Traceback (most recent call last):
  File "C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python\qgis\utils.py", line 228, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/21   /.qgis2/python/plugins\quick_map_services\quick_map_services.py", line 112, in initGui
    self.build_menu_tree()
  File "C:/Users/21   /.qgis2/python/plugins\quick_map_services\quick_map_services.py", line 232, in build_menu_tree
    self.groups_list = DsGroupsList(self.locale, self.custom_translator)
  File "C:/Users/21   /.qgis2/python/plugins\quick_map_services\ds_groups_list.py", line 46, in init
    self._fill_groups_list()
  File "C:/Users/21   /.qgis2/python/plugins\quick_map_services\ds_groups_list.py", line 53, in _fill_groups_list
    self._read_ini_file(root, ini_file)
  File "C:/Users/21   /.qgis2/python/plugins\quick_map_services\ds_groups_list.py", line 75, in _read_ini_file
    error_message = 'Group INI file can\'t be parsed: ' + e.message
  File "C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python\qgis\utils.py", line 55, in showWarning
    "warning:%s\ntraceback:%s" % ( warnings.formatwarning(message, category, filename, lineno), stk),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 19: ordinal not in range(128)
```
