### ISSUE TITLE
qgis crash on save settings of plugin

### ISSUE THREAD

**Issue by rduivenvoorde** [nextgis/quickmapservices#33]
Current dev version of QGIS (self compiled Debian Testing), crashes when I go to settings (empty project and push the save button. No python msg show, just full stop.

Not sure if it is only my system...

Tried to start with gdb, but could not see something interesting

```
src/gui/qgsmapcanvas.cpp: 644: (refresh) [467ms] CANVAS refresh scheduling
src/gui/qgsmapcanvas.cpp: 654: (refreshMap) [2ms] CANVAS refresh!
src/core/qgsmaprenderersequentialjob.cpp: 29: (QgsMapRendererSequentialJob) [0ms] SEQUENTIAL construct
src/core/qgsmaprenderersequentialjob.cpp: 62: (start) [1ms] SEQUENTIAL START
src/core/qgsmaprenderercustompainterjob.cpp: 32: (QgsMapRendererCustomPainterJob) [0ms] QPAINTER construct
src/core/qgsmaprenderercustompainterjob.cpp: 56: (start) [0ms] QPAINTER run!
src/core/qgsmaprenderercustompainterjob.cpp: 58: (start) [0ms] Preparing list of layer jobs for rendering
src/core/qgsmaprendererjob.cpp: 149: (prepareJobs) [5ms] CACHE VALID: 0
src/core/qgsmaprenderercustompainterjob.cpp: 84: (start) [0ms] Rendering prepared in (seconds): 0.005
src/core/qgsmaprenderercustompainterjob.cpp: 211: (doRender) [0ms] [thread:0x850a4c0] Starting to render layer stack.
src/core/qgsmaprenderercustompainterjob.cpp: 240: (doRender) [0ms] [thread:0x850a4c0] Done rendering map layers
src/core/qgsmaprenderercustompainterjob.cpp: 251: (drawLabeling) [0ms] [thread:0x850a4c0] Draw labeling start
src/core/qgsmaprenderercustompainterjob.cpp: 269: (drawLabeling) [0ms] [thread:0x850a4c0] Draw labeling took (seconds): 0
src/core/qgsmaprenderercustompainterjob.cpp: 245: (doRender) [0ms] [thread:0x850a4c0] Rendering completed in (seconds): 0
src/core/qgsmaprenderercustompainterjob.cpp: 180: (futureFinished) [4ms] QPAINTER futureFinished
src/core/qgsmaprenderersequentialjob.cpp: 121: (internalFinished) [0ms] SEQUENTIAL finished
src/gui/qgsmapcanvas.cpp: 695: (rendererJobFinished) [0ms] CANVAS finish! 1
src/core/qgsmaprenderercustompainterjob.cpp: 37: (~QgsMapRendererCustomPainterJob) [17ms] QPAINTER destruct
src/core/qgsmaprenderersequentialjob.cpp: 38: (~QgsMapRendererSequentialJob) [8ms] SEQUENTIAL destruct

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff2424d5f in QMetaObject::changeGuard(QObject**, QObject*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
(gdb) bt
#0  0x00007ffff2424d5f in QMetaObject::changeGuard(QObject**, QObject*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#1  0x00007ffff1baf56d in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#2  0x00007fff7be3606b in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtGui.so
#3  0x00007ffff17acaf8 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#4  0x00007ffff1bb353b in QMenu::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#5  0x00007fff7be34b1b in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtGui.so
#6  0x00007ffff17567bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#7  0x00007ffff175d43f in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#8  0x00007ffff2c4d4f7 in QgsApplication::notify (this=0x7fffffffd640, receiver=0x60125c0, event=0x7fffffffcd00) at /home/richard/dev/qgis/git/qgis/src/core/qgsapplication.cpp:253
#9  0x00007ffff240c36d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#10 0x00007ffff175ca9f in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#11 0x00007ffff17d6bca in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#12 0x00007ffff17d522c in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#13 0x00007ffff17fe2d2 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#14 0x00007fffed229c3d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007fffed229f20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007fffed229fcc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff243b98d in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#18 0x00007ffff17fe396 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#19 0x00007ffff240aec1 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#20 0x00007ffff240b225 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#21 0x00007ffff2410ca9 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#22 0x00000000004c8786 in main (argc=1, argv=0x7fffffffe1a8) at /home/richard/dev/qgis/git/qgis/src/app/main.cpp:1048
(gdb) step
Single stepping until exit from function _ZN11QMetaObject11changeGuardEPP7QObjectS1_,
which has no line number information.
[Thread 0x7ffff7f86200 (LWP 4981) exited]
[Thread 0x7fff65551700 (LWP 5010) exited]
[Thread 0x7fff6d1fb700 (LWP 5009) exited]
[Thread 0x7fff8f0d0700 (LWP 4991) exited]
[Thread 0x7fff8fd7a700 (LWP 4990) exited]
[Thread 0x7fff9057b700 (LWP 4989) exited]
[Thread 0x7fffd19b9700 (LWP 4988) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
```

**Comment by yellow-sky** [comment]
Do you get this crash if plugin is disabled?

**Comment by rduivenvoorde** [comment]
I did some further testing.

If I start QGIS with: "qgis --configpath /tmp/foo"  (fresh environment), install the plugin and then save, all is ok

BUT as soon as I set some crs options, like Options/CRS 'Enable on the fly by default' and the Always start new project with the follwoing crs (EPSG:28992), and 'CRS for new layers' put on EPGS:28992
THEN after downloading user contributed file... save, crash.. but not always

**Comment by pcav** [comment]
Confirmed here, hard crash.

**Comment by rduivenvoorde** [comment]
Ubuntu 14.04 also affected according to people on IRC

**Comment by OnkelTem** [comment]
Crash
ubuntu 14.04
QGIS 2.12.1-Lyon
QMS 0.15

**Comment by simgislab** [comment]
Confirmed. 

I have exactly the same configuration as @OnkelTem and saving configuration crashes QMS, but only sometimes (if I repeatedly download pack/save it crashes once in 5 times). 

@yellow-sky please have a look.

Here are the steps following @rduivenvoorde recipe :

1. qgis --configpath /tmp/foo
1. Install QMS
1. Settings/Options/CRS 'Enable on the fly by default' and the Always start new project. Set both to EPSG:28992
1. QMS/Settins/Download contributed pack. Save
1. Repeate previous step until you get a crash.

**Comment by ecodiv** [comment]
For me QGIS crashes (without any message) after step 2 (installation of QMS), or, if QMS is installed, after enabling the plugin. I am on Ubuntu 14.04, latest QGISdev or QGIS 2.12 both self compiled.

**Comment by simgislab** [comment]
reopen if necessary
