### ISSUE TITLE
Plugin load error when non-ASCII characters exists in qgis user directory path.

### ISSUE THREAD

**Issue by jekhor** [nextgis/quickmapservices#46]
When trying to install plugin at Windows 7 with russian locale and user name contains cyrillic letters, error message is displayed:

```
Не удалось загрузить модуль quick_map_services из-за ошибки при вызове его метода initGui()


Traceback (most recent call last):
  File "C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python\qgis\utils.py", line 228, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/21   /.qgis2/python/plugins\quick_map_services\quick_map_services.py", line 112, in initGui
    self.build_menu_tree()
  File "C:/Users/21   /.qgis2/python/plugins\quick_map_services\quick_map_services.py", line 232, in build_menu_tree
    self.groups_list = DsGroupsList(self.locale, self.custom_translator)
  File "C:/Users/21   /.qgis2/python/plugins\quick_map_services\ds_groups_list.py", line 46, in init
    self._fill_groups_list()
  File "C:/Users/21   /.qgis2/python/plugins\quick_map_services\ds_groups_list.py", line 53, in _fill_groups_list
    self._read_ini_file(root, ini_file)
  File "C:/Users/21   /.qgis2/python/plugins\quick_map_services\ds_groups_list.py", line 75, in _read_ini_file
    error_message = 'Group INI file can\'t be parsed: ' + e.message
  File "C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python\qgis\utils.py", line 55, in showWarning
    "warning:%s\ntraceback:%s" % ( warnings.formatwarning(message, category, filename, lineno), stk),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 19: ordinal not in range(128)


Версия Python:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


Версия:
2.8.4-Wien Wien, 71ba2c7
```

**Comment by simgislab** [comment]
dup #28
