### ISSUE TITLE
After update: No module named urllib3

### ISSUE THREAD

**Issue by blackgis** [nextgis/quickmapservices#85]
No module named urllib3

I use windows and the last stable version 1.14.3 of QGIS.

How can I/you fix this issue?

Thx in advance.

**Comment by simgislab** [comment]
latest QMS?

**Comment by blackgis** [comment]
installed version: 0.17.3 (which causes this issue), Version 0.17.2 worked perfect.

**Comment by blackgis** [comment]
This is the QGIS Python Error log:
2016-06-08T14:48:08	1	Traceback (most recent call last):
			  File "C:/BLACKP~1/QGIS_Program/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 306, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/Users/Richard/.qgis2/python/plugins\quick_map_services\__init__.py", line 34, in classFactory
			    from .quick_map_services import QuickMapServices
			  File "C:/BLACKP~1/QGIS_Program/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/Richard/.qgis2/python/plugins\quick_map_services\quick_map_services.py", line 39, in <module>
			    from qms_service_toolbox import QmsServiceToolbox
			  File "C:/BLACKP~1/QGIS_Program/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/Richard/.qgis2/python/plugins\quick_map_services\qms_service_toolbox.py", line 10, in <module>
			    from .qms_external_api_python.client import Client
			  File "C:/BLACKP~1/QGIS_Program/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/Richard/.qgis2/python/plugins\quick_map_services\qms_external_api_python\client.py", line 1, in <module>
			    from api.api_v1 import ApiClientV1 as Client
			  File "C:/BLACKP~1/QGIS_Program/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/Richard/.qgis2/python/plugins\quick_map_services\qms_external_api_python\api\api_v1.py", line 1, in <module>
			    from .api_abstract import ApiClient
			  File "C:/BLACKP~1/QGIS_Program/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/Richard/.qgis2/python/plugins\quick_map_services\qms_external_api_python\api\api_abstract.py", line 1, in <module>
			    from ..requests import get
			  File "C:/BLACKP~1/QGIS_Program/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/Richard/.qgis2/python/plugins\quick_map_services\qms_external_api_python\requests\__init__.py", line 61, in <module>
			    from .packages.urllib3.exceptions import DependencyWarning
			  File "C:/BLACKP~1/QGIS_Program/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/Richard/.qgis2/python/plugins\quick_map_services\qms_external_api_python\requests\packages\__init__.py", line 29, in <module>
			    import urllib3
			  File "C:/BLACKP~1/QGIS_Program/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			ImportError: No module named urllib3

**Comment by yellow-sky** [comment]
Try to full reinstall plugin

**Comment by blackgis** [comment]
Same error. As I said before it worked perfectly.

**Comment by blackgis** [comment]
I missed some libs in the osgeo4w installer - now it works after reinstalling(via osgeo4w) and adding the missing libs (all python libs in the osgeo4w installer). You can close this issue!

**Comment by simgislab** [comment]
thanks for letting us know!
