### ISSUE TITLE
Problems when manualy upgrading to python 2.7.5

### ISSUE THREAD

**Issue by JackAndersen** [nextgis/quickmapservices#94]
I manually upgraded python to 2.7.5 to make some other plugins work with the new Sentinel datahub (satelite data). However this has broken this plugin. Is there a way to make Quickmapservices work with a newer python version? This is perhaps especially important when the change to QGIS 3.0 and python 3.0 will take place within the next 8 months :-)

Here is the error log:

Couldn't load plugin quick_map_services due to an error when calling its classFactory() method 

ImportError: No module named requests 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/B020719/.qgis2/python/plugins\quick_map_services__init__.py", line 34, in classFactory
    from .quick_map_services import QuickMapServices
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/B020719/.qgis2/python/plugins\quick_map_services\quick_map_services.py", line 39, in 
    from qms_service_toolbox import QmsServiceToolbox
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/B020719/.qgis2/python/plugins\quick_map_services\qms_service_toolbox.py", line 10, in 
    from .qms_external_api_python.client import Client
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/B020719/.qgis2/python/plugins\quick_map_services\qms_external_api_python\client.py", line 1, in 
    from api.api_v1 import ApiClientV1 as Client
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/B020719/.qgis2/python/plugins\quick_map_services\qms_external_api_python\api\api_v1.py", line 1, in 
    from .api_abstract import ApiClient
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/B020719/.qgis2/python/plugins\quick_map_services\qms_external_api_python\api\api_abstract.py", line 4, in 
    from requests import get
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named requests

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.16.0-Nødebo Nødebo, d0b3e39 

Python Path:
C:/Users/B020719/.qgis2/python/plugins\processing_prepair
C:/PROGRA~1/QGISNO~1/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGISNO~1/apps/qgis/./python
C:/Users/B020719/.qgis2/python
C:/Users/B020719/.qgis2/python/plugins
C:/PROGRA~1/QGISNO~1/apps/qgis/./python/plugins
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
C:\PROGRA~1\QGISNO~1\bin\python27.zip
C:\PROGRA~1\QGISNO~1\apps\Python27\DLLs
C:\PROGRA~1\QGISNO~1\apps\Python27\lib
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\plat-win
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGISNO~1\bin
C:\PROGRA~1\QGISNO~1\apps\Python27
c:\progra~1\qgisno~1\apps\python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
c:\progra~1\qgisno~1\apps\python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
c:\progra~1\qgisno~1\apps\python27\lib\site-packages\pytz-2012j-py2.7.egg
c:\progra~1\qgisno~1\apps\python27\lib\site-packages\shapely-1.2.18-py2.7-win-amd64.egg
c:\progra~1\qgisno~1\apps\python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
c:\progra~1\qgisno~1\apps\python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:/Users/B020719/.qgis2//python
C:\Users\B020719.qgis2\python\plugins\SelectTools/tools

**Comment by yellow-sky** [comment]
are you using the latest version of the plugin?

**Comment by JackAndersen** [comment]
Thank you for the quick reply, yes v.  0.17.4.

I tried manually installing the request repo using the PIP python installer. However for som reason this broke matplotlib and QGIS wouldn't not start. Next i tried installing matplotlib and request using the PIP installer and QGIS loaded fine however now it says that both Quickmapservices and some other plugins are broken and i get the same error as before.

- Jack

**Comment by JackAndersen** [comment]
Update, it also was missing the urlib3 package i used the PIP installer to update this and a new error came up:

Couldn't load plugin quick_map_services due to an error when calling its classFactory() method 

ImportError: cannot import name _compare_digest 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/B020719/.qgis2/python/plugins\quick_map_services\__init__.py", line 34, in classFactory
    from .quick_map_services import QuickMapServices
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/B020719/.qgis2/python/plugins\quick_map_services\quick_map_services.py", line 39, in 
    from qms_service_toolbox import QmsServiceToolbox
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/B020719/.qgis2/python/plugins\quick_map_services\qms_service_toolbox.py", line 10, in 
    from .qms_external_api_python.client import Client
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/B020719/.qgis2/python/plugins\quick_map_services\qms_external_api_python\client.py", line 1, in 
    from api.api_v1 import ApiClientV1 as Client
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/B020719/.qgis2/python/plugins\quick_map_services\qms_external_api_python\api\api_v1.py", line 1, in 
    from .api_abstract import ApiClient
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/B020719/.qgis2/python/plugins\quick_map_services\qms_external_api_python\api\api_abstract.py", line 4, in 
    from requests import get
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\requests-2.10.0-py2.7.egg\requests\__init__.py", line 61, in 
    from .packages.urllib3.exceptions import DependencyWarning
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\requests-2.10.0-py2.7.egg\requests\packages\__init__.py", line 29, in 
    import urllib3
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\urllib3\__init__.py", line 8, in 
    from .connectionpool import (
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\urllib3\connectionpool.py", line 35, in 
    from .connection import (
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\urllib3\connection.py", line 44, in 
    from .util.ssl_ import (
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\urllib3\util\__init__.py", line 6, in 
    from .ssl_ import (
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\urllib3\util\ssl_.py", line 4, in 
    import hmac
  File "C:/PROGRA~1/QGISNO~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGISNO~1\apps\Python27\lib\hmac.py", line 8, in 
    from operator import _compare_digest as compare_digest
ImportError: cannot import name _compare_digest


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.16.0-Nødebo Nødebo, d0b3e39 

Python Path:
C:/Users/B020719/.qgis2/python/plugins\processing_prepair
C:/PROGRA~1/QGISNO~1/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGISNO~1/apps/qgis/./python
C:/Users/B020719/.qgis2/python
C:/Users/B020719/.qgis2/python/plugins
C:/PROGRA~1/QGISNO~1/apps/qgis/./python/plugins
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\requests-2.10.0-py2.7.egg
C:\PROGRA~1\QGISNO~1\bin\python27.zip
C:\PROGRA~1\QGISNO~1\apps\Python27\DLLs
C:\PROGRA~1\QGISNO~1\apps\Python27\lib
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\plat-win
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGISNO~1\bin
C:\PROGRA~1\QGISNO~1\apps\Python27
c:\progra~1\qgisno~1\apps\python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
c:\progra~1\qgisno~1\apps\python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
c:\progra~1\qgisno~1\apps\python27\lib\site-packages\shapely-1.2.18-py2.7-win-amd64.egg
c:\progra~1\qgisno~1\apps\python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
c:\progra~1\qgisno~1\apps\python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGISNO~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:/Users/B020719/.qgis2//python
C:\Users\B020719\.qgis2\python\plugins\SelectTools/tools

**Comment by simgislab** [comment]
it seems like you might want to try even newer Python, but this might break everything completely

http://stackoverflow.com/questions/26535043/python-flask-error-importerror-cannot-import-name-compare-digest

**Comment by simgislab** [comment]
particular deployment issue
